from __future__ import annotations

from dataclasses import dataclass
from dataclasses import field as dataclass_field
from typing import Any


@dataclass(frozen=True)
class TargetField:
    table: str
    field: str
    required: bool
    data_type: str
    nullable: bool
    validation_kind: str
    description: str
    expected_evidence: list[str] = dataclass_field(default_factory=list)
    allowed_values: list[str] = dataclass_field(default_factory=list)
    generated: bool = False


TARGET_SCHEMA: list[TargetField] = [
    TargetField(
        table="members",
        field="member_id",
        required=True,
        data_type="identifier",
        nullable=False,
        validation_kind="member_identifier",
        description="Stable unique identifier for the member/person.",
        expected_evidence=["high uniqueness", "ID-like values", "member id aliases"],
    ),
    TargetField(
        table="members",
        field="first_name",
        required=True,
        data_type="text",
        nullable=False,
        validation_kind="person_name",
        description="Member first name.",
        expected_evidence=["person-name text", "first name aliases"],
    ),
    TargetField(
        table="members",
        field="last_name",
        required=True,
        data_type="text",
        nullable=False,
        validation_kind="person_name",
        description="Member last name.",
        expected_evidence=["person-name text", "last name aliases"],
    ),
    TargetField(
        table="members",
        field="date_of_birth",
        required=True,
        data_type="date",
        nullable=False,
        validation_kind="date_of_birth",
        description="Member date of birth, normalized to YYYY-MM-DD.",
        expected_evidence=["date-like values", "realistic ages 0-120", "DOB aliases"],
    ),
    TargetField(
        table="members",
        field="gender",
        required=False,
        data_type="enum",
        nullable=True,
        validation_kind="gender",
        description="Normalized member gender.",
        expected_evidence=["values such as M, F, Male, Female, Other"],
        allowed_values=["male", "female", "other", "unknown"],
    ),
    TargetField(
        table="members",
        field="email",
        required=False,
        data_type="email",
        nullable=True,
        validation_kind="email",
        description="Member email address.",
        expected_evidence=["email-like values", "email aliases"],
    ),
    TargetField(
        table="members",
        field="phone",
        required=False,
        data_type="phone",
        nullable=True,
        validation_kind="phone",
        description="Member phone number.",
        expected_evidence=["phone-like values", "phone aliases"],
    ),
    TargetField(
        table="plans",
        field="plan_id",
        required=True,
        data_type="identifier",
        nullable=False,
        validation_kind="plan_identifier",
        description="Stable plan code or identifier.",
        expected_evidence=["code-like values", "repeated plan codes"],
    ),
    TargetField(
        table="plans",
        field="plan_name",
        required=True,
        data_type="text",
        nullable=False,
        validation_kind="plan_name",
        description="Human-readable plan name.",
        expected_evidence=["repeated descriptive plan names"],
    ),
    TargetField(
        table="plans",
        field="plan_type",
        required=False,
        data_type="enum",
        nullable=True,
        validation_kind="plan_type",
        description="Normalized plan type.",
        expected_evidence=["values such as PPO, HMO, EPO, HDHP"],
        allowed_values=["PPO", "HMO", "EPO", "HDHP", "POS"],
    ),
    TargetField(
        table="plans",
        field="carrier_name",
        required=False,
        data_type="text",
        nullable=True,
        validation_kind="organization_name",
        description="Carrier or payer name.",
        expected_evidence=["repeated organization-like text"],
    ),
    TargetField(
        table="member_coverage",
        field="coverage_id",
        required=True,
        data_type="identifier",
        nullable=False,
        validation_kind="generated_identifier",
        description="Generated coverage relationship identifier.",
        expected_evidence=["generated by the application"],
        generated=True,
    ),
    TargetField(
        table="member_coverage",
        field="member_id",
        required=True,
        data_type="identifier",
        nullable=False,
        validation_kind="member_identifier",
        description="Member identifier for the coverage relationship.",
        expected_evidence=["same source as members.member_id"],
    ),
    TargetField(
        table="member_coverage",
        field="plan_id",
        required=True,
        data_type="identifier",
        nullable=False,
        validation_kind="plan_identifier",
        description="Plan identifier for the coverage relationship.",
        expected_evidence=["same source as plans.plan_id"],
    ),
    TargetField(
        table="member_coverage",
        field="coverage_start_date",
        required=True,
        data_type="date",
        nullable=False,
        validation_kind="coverage_start_date",
        description="Eligibility or coverage start date.",
        expected_evidence=["date-like values", "effective date aliases"],
    ),
    TargetField(
        table="member_coverage",
        field="coverage_end_date",
        required=False,
        data_type="date",
        nullable=True,
        validation_kind="coverage_end_date",
        description="Eligibility or coverage end date.",
        expected_evidence=["date-like values", "term date aliases", "nullable"],
    ),
    TargetField(
        table="member_coverage",
        field="coverage_status",
        required=True,
        data_type="enum",
        nullable=False,
        validation_kind="coverage_status",
        description="Normalized coverage status.",
        expected_evidence=["values such as Active, Termed, Pending"],
        allowed_values=["active", "terminated", "pending", "cancelled"],
    ),
    TargetField(
        table="member_coverage",
        field="relationship_to_subscriber",
        required=True,
        data_type="enum",
        nullable=False,
        validation_kind="relationship_to_subscriber",
        description="Relationship between the member and subscriber.",
        expected_evidence=["values such as Self, Spouse, Child, Dependent"],
        allowed_values=["self", "spouse", "child", "dependent"],
    ),
    TargetField(
        table="member_coverage",
        field="subscriber_id",
        required=False,
        data_type="identifier",
        nullable=True,
        validation_kind="subscriber_identifier",
        description="Subscriber identifier, required for dependents.",
        expected_evidence=["ID-like values", "may repeat across dependents"],
    ),
]

TARGET_FIELDS_BY_KEY: dict[tuple[str, str], TargetField] = {
    (field.table, field.field): field for field in TARGET_SCHEMA
}

TARGET_FIELDS_BY_FIELD: dict[str, TargetField] = {}
for target_field in TARGET_SCHEMA:
    TARGET_FIELDS_BY_FIELD.setdefault(target_field.field, target_field)


FIELD_ALIASES: dict[str, list[str]] = {
    "member_id": [
        "member id",
        "member number",
        "member no",
        "mbr id",
        "patient id",
        "person id",
        "employee id",
    ],
    "first_name": ["first name", "first", "fname", "given name"],
    "last_name": ["last name", "last", "lname", "surname", "family name"],
    "date_of_birth": [
        "dob",
        "date of birth",
        "birth date",
        "birthdate",
        "member dob",
        "patient birthdate",
    ],
    "gender": ["gender", "sex"],
    "email": ["email", "email address", "member email"],
    "phone": ["phone", "phone number", "mobile", "cell"],
    "plan_id": ["plan id", "plan code", "benefit plan", "product code"],
    "plan_name": ["plan", "plan name", "benefit name", "product name"],
    "plan_type": ["plan type", "product type", "network type"],
    "carrier_name": ["carrier", "carrier name", "payer", "payer name"],
    "coverage_start_date": [
        "effective date",
        "eff date",
        "start date",
        "coverage start date",
        "eligibility start date",
    ],
    "coverage_end_date": [
        "term date",
        "termination date",
        "end date",
        "coverage end date",
        "eligibility end date",
    ],
    "coverage_status": [
        "status",
        "coverage status",
        "eligibility status",
        "enrollment status",
    ],
    "relationship_to_subscriber": [
        "relationship",
        "relation",
        "relationship to subscriber",
        "dependent relationship",
    ],
    "subscriber_id": ["subscriber id", "subscriber number", "primary member id", "employee id"],
}

FIELD_TABLES: dict[str, list[str]] = {
    "members": [
        "member_id",
        "first_name",
        "last_name",
        "date_of_birth",
        "gender",
        "email",
        "phone",
    ],
    "plans": ["plan_id", "plan_name", "plan_type", "carrier_name"],
    "member_coverage": [
        "coverage_id",
        "member_id",
        "plan_id",
        "coverage_start_date",
        "coverage_end_date",
        "coverage_status",
        "relationship_to_subscriber",
        "subscriber_id",
    ],
}

GENDER_NORMALIZATION = {
    "m": "male",
    "male": "male",
    "f": "female",
    "female": "female",
    "o": "other",
    "other": "other",
    "u": "unknown",
    "unknown": "unknown",
    "x": "unknown",
}

COVERAGE_STATUS_NORMALIZATION = {
    "a": "active",
    "active": "active",
    "t": "terminated",
    "term": "terminated",
    "termed": "terminated",
    "terminated": "terminated",
    "p": "pending",
    "pending": "pending",
    "c": "cancelled",
    "cancelled": "cancelled",
    "canceled": "cancelled",
}

RELATIONSHIP_NORMALIZATION = {
    "self": "self",
    "subscriber": "self",
    "employee": "self",
    "spouse": "spouse",
    "child": "child",
    "dependent": "dependent",
}

PLAN_TYPE_NORMALIZATION = {
    "ppo": "PPO",
    "p p o": "PPO",
    "ppo plan": "PPO",
    "hmo": "HMO",
    "h m o": "HMO",
    "epo": "EPO",
    "e p o": "EPO",
    "hdhp": "HDHP",
    "high deductible": "HDHP",
    "high deductible health plan": "HDHP",
    "pos": "POS",
}

ENUM_NORMALIZERS: dict[str, dict[str, str]] = {
    "gender": GENDER_NORMALIZATION,
    "coverage_status": COVERAGE_STATUS_NORMALIZATION,
    "relationship_to_subscriber": RELATIONSHIP_NORMALIZATION,
    "plan_type": PLAN_TYPE_NORMALIZATION,
}


def target_schema_payload() -> list[dict[str, Any]]:
    return [
        {
            "table": field.table,
            "field": field.field,
            "required": field.required,
            "data_type": field.data_type,
            "nullable": field.nullable,
            "validation_kind": field.validation_kind,
            "allowed_values": field.allowed_values,
            "description": field.description,
            "expected_evidence": field.expected_evidence,
        }
        for field in TARGET_SCHEMA
        if not field.generated
    ]


def required_target_fields() -> list[TargetField]:
    return [field for field in TARGET_SCHEMA if field.required and not field.generated]
